name: Java CI with SonarCube and Jacoco

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B verify

      - name: SonarCube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.projectKey=SupplyChainX
            -Dsonar.projectName=SupplyChainX
            -Dsonar.organization=your-org-name # Ajoutez si vous utilisez SonarCloud
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=http://localhost:9000 # Répétition de l'URL du serveur